name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: ${{ matrix.node-version == '16.x' && 'true' || 'false' }}
    - run: npm ci
    - run: npm test
    - name: Run NexiDyn (Smoke Test)
      run: node bin/nexidyn.js --version

  check-changes:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && always()

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Debug SHA values
      run: |
        echo "Previous SHA: ${{ github.event.before }}"
        echo "Current SHA: ${{ github.sha }}"
    - name: Check for changes
      run: |
        PREVIOUS_SHA="${{ github.event.before }}"
        CURRENT_SHA="${{ github.sha }}"
        
        if [ -n "$PREVIOUS_SHA" ] && [ "$PREVIOUS_SHA" != "0000000000000000000000000000000000000000" ]; then
          if git rev-parse --quiet --verify "$PREVIOUS_SHA^{commit}" >/dev/null 2>&1; then
            echo "Comparing changes between $PREVIOUS_SHA and $CURRENT_SHA"
            git diff --name-only $PREVIOUS_SHA $CURRENT_SHA || echo "No changes detected or error occurred"
          else
            echo "Previous commit $PREVIOUS_SHA not found. Listing all changed files in this push:"
            git diff-tree --no-commit-id --name-only -r $CURRENT_SHA
          fi
        else
          echo "Unable to determine previous commit. Listing all changed files in this push:"
          git diff-tree --no-commit-id --name-only -r $CURRENT_SHA
        fi
    - name: List changed files
      run: |
        PREVIOUS_SHA="${{ github.event.before }}"
        CURRENT_SHA="${{ github.sha }}"
        
        echo "Changed files:"
        if [ -n "$PREVIOUS_SHA" ] && [ "$PREVIOUS_SHA" != "0000000000000000000000000000000000000000" ]; then
          if git rev-parse --quiet --verify "$PREVIOUS_SHA^{commit}" >/dev/null 2>&1; then
            git diff --name-only $PREVIOUS_SHA $CURRENT_SHA || echo "No changes detected or error occurred"
          else
            git diff-tree --no-commit-id --name-only -r $CURRENT_SHA
          fi
        else
          git diff-tree --no-commit-id --name-only -r $CURRENT_SHA
        fi
    - name: Check for package.json changes
      run: |
        PREVIOUS_SHA="${{ github.event.before }}"
        CURRENT_SHA="${{ github.sha }}"
        
        if [ -n "$PREVIOUS_SHA" ] && [ "$PREVIOUS_SHA" != "0000000000000000000000000000000000000000" ]; then
          if git rev-parse --quiet --verify "$PREVIOUS_SHA^{commit}" >/dev/null 2>&1; then
            if git diff --name-only $PREVIOUS_SHA $CURRENT_SHA | grep -q "package.json"; then
              echo "package.json has changed. Consider updating the version."
            else
              echo "package.json has not changed."
            fi
          else
            if git diff-tree --no-commit-id --name-only -r $CURRENT_SHA | grep -q "package.json"; then
              echo "package.json has changed. Consider updating the version."
            else
              echo "package.json has not changed."
            fi
          fi
        else
          if git diff-tree --no-commit-id --name-only -r $CURRENT_SHA | grep -q "package.json"; then
            echo "package.json has changed. Consider updating the version."
          else
            echo "package.json has not changed."
          fi
        fi